#!/bin/bash

directory="/user/hive-ingest-users/data";

cat > query.hql <<EOF
DROP TABLE incremental_table;
CREATE EXTERNAL TABLE IF NOT EXISTS incremental_table(
		State CHAR(2),
		CMS_Certification_Number_CCN INT,
		Provider_Name STRING,
		Address STRING,
		City STRING,
		Zip INT,
		Phone STRING,
		Type_of_Ownership STRING,
		Offers_Nursing_Care_Services STRING,
		Offers_Physical_Therapy_Services STRING,
		Offers_Occupational_Therapy_Services STRING,
		Offers_Speech_Pathology_Services STRING,
		Offers_Medical_Social_Services STRING,
		Offers_Home_Health_Aide_Services STRING,
		Date_Certified STRING,
		Quality_of_Patient_Care_Star_Rating STRING,
		Footnote_Quality_of_Patient_Care_Star_Rating STRING,
		How_often_the_home_health_team_began_their_patients_care_in_a_timely_manner STRING,
		Footnote_for_how_often_the_home_health_team_began_their_patients_care_in_a_timely_manner STRING,
		How_often_the_home_health_team_taught_patients_or_their_family_caregivers_about_their_drugs STRING,
		Footnote_for_how_often_the_home_health_team_taught_patients_or_their_family_caregivers_about_their_drugs STRING,
		How_often_the_home_health_team_checked_patients_risk_of_falling STRING,
		Footnote_for_how_often_the_home_health_team_checked_patients_risk_of_falling STRING,
		How_often_the_home_health_team_checked_patients_for_depression STRING,
		Footnote_for_how_often_the_home_health_team_checked_patients_for_depression STRING,
		How_often_the_home_health_team_made_sure_that_their_patients_have_received_a_flu_shot_for_the_current_flu_season STRING,
		Footnote_for_how_often_the_home_health_team_made_sure_that_their_patients_have_received_a_flu_shot_for_the_current_flu_season STRING,
		How_often_the_home_health_team_made_sure_that_their_patients_have_received_a_pneumococcal_vaccine_pneumonia_shot STRING,
		Footnote_as_how_often_the_home_health_team_made_sure_that_their_patients_have_received_a_pneumococcal_vaccine_pneumonia_shot STRING,
		With_diabetes_how_often_the_home_health_team_got_doctors_orders_gave_foot_care_and_taught_patients_about_foot_care STRING,
		Footnote_for_how_often_the_home_health_team_got_doctors_orders_gave_foot_care_and_taught_patients_about_foot_care STRING,
		How_often_the_home_health_team_checked_patients_for_pain STRING,
		Footnote_for_how_often_the_home_health_team_checked_patients_for_pain STRING,
		How_often_the_home_health_team_treated_their_patients_pain STRING,
		Footnote_for_often_the_home_health_team_treated_their_patients_pain STRING,
		How_often_the_home_health_team_treated_heart_failure_weakening_of_the_heart_patients_symptoms STRING,
		Footnote_for_how_often_the_home_health_team_treated_heart_failure_weakening_of_the_heart_patients_symptoms STRING,
		How_often_the_home_health_team_took_doctorordered_action_to_prevent_pressure_sores_bed_sores STRING,
		Footnote_for_how_often_the_home_health_team_took_doctorordered_action_to_prevent_pressure_sores_bed_sores STRING,
		How_often_the_home_health_team_included_treatments_to_prevent_pressure_sores_bed_sores_in_the_plan_of_care STRING,
		Footnote_for_how_often_the_home_health_team_included_treatments_to_prevent_pressure_sores_bed_sores_in_the_plan_of_care STRING,
		How_often_the_home_health_team_checked_patients_for_the_risk_of_developing_pressure_sores_bed_sores STRING,
		Footnote_for_how_often_the_home_health_team_checked_patients_for_the_risk_of_developing_pressure_sores_bed_sores STRING,
		How_often_patients_got_better_at_walking_or_moving_around STRING,
		Footnote_for_how_often_patients_got_better_at_walking_or_moving_around STRING,
		How_often_patients_got_better_at_getting_in_and_out_of_bed STRING,
		Footnote_for_how_often_patients_got_better_at_getting_in_and_out_of_bed STRING,
		How_often_patients_got_better_at_bathing STRING,
		Footnote_for_how_often_patients_got_better_at_bathing STRING,
		How_often_patients_had_less_pain_when_moving_around STRING,
		Footnote_for_how_often_patients_had_less_pain_when_moving_around STRING,
		How_often_patients_breathing_improved STRING,
		Footnote_for_how_often_patients_breathing_improved STRING,
		How_often_patients_wounds_improved_or_healed_after_an_operation STRING,
		Footnote_for_how_often_patients_wounds_improved_or_healed_after_an_operation STRING,
		How_often_patients_got_better_at_taking_their_drugs_correctly_by_mouth STRING,
		Footnote_for_how_often_patients_got_better_at_taking_their_drugs_correctly_by_mouth STRING,
		How_often_home_health_patients_had_to_be_admitted_to_the_hospital STRING,
		Footnote_for_how_often_home_health_patients_had_to_be_admitted_to_the_hospital STRING,
		How_often_patients_receiving_home_health_care_needed_urgent_unplanned_care_in_the_ER_without_being_admitted STRING,
		Footnote_for_how_often_patients_receiving_home_health_care_needed_urgent_unplanned_care_in_the_ER_without_being_admitted STRING,
		How_often_home_health_patients_who_have_had_a_recent_hospital_stay_had_to_be_readmitted_to_the_hospital STRING,
		Footnote_for_how_often_home_health_patients_who_have_had_a_recent_hospital_stay_had_to_be_readmitted_to_the_hospital STRING,
		How_often_home_health_patients_who_have_had_a_recent_hospital STRING,
		Footnote_for_how_often_home_health_patients_who_have_had_a_recent_hospital STRING,
		Footnote STRING,
		dt STRING)
    COMMENT 'Data about Home Health Care Agencies database'
    ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t'
    STORED AS TEXTFILE
    location '$directory';

EOF
hive -f query.hql;
rm -rf query.hql;
